### PR TITLE
Add dockerfiles make work in compose

### PR DESCRIPTION
**Pull request by genevera**
Creates Dockerfiles to build images, adjusts `compose.yml` to launch the web app, and makes some adjustments to the analysis script that populates the `transcribed` table.

### CODE REVIEW

**Comment by genevera** [comment]
Fixes #1

**Comment by arcyleung** [comment]
Thanks for your PR and it looks good!

I have been thinking the analyze.py can run in a cron job on a fixed interval, and update the transcriptions table as events get recorded.

**Review by arcyleung — APPROVED** [review]

**Comment by genevera** [comment]
No worries!  `analyze.py` could be modified such that it monitors the frigate topic in mqtt stream and puts new snapshots into a queue for captioning as they pop up.  You could just run it in a always-restart service or container; it wouldn't need cron since it would always be monitoring.

**Comment by genevera** [comment]
PS - I don't have write access so I can't merge this.

**Comment by arcyleung** [comment]
> PS - I don't have write access so I can't merge this.

Apologies, I have added you now and merged this

**Pull request merged**
